### ISSUE TITLE
layout of 'maps overview' page is overwhelming

### ISSUE THREAD

**Issue by amcooksey** [legumeinfo/legumeinfo.org#8]
Same information can be obtained elsewhere in a simpler display (Interactive maps link).

**Comment by amcooksey** [comment]
This issue also applies to PeanutBase.

**Comment by ekcannon** [comment]
What should be on this page? Thoughts:

  * Explanation of map and mapping population names. 
  * Link to search (Or embed search? Not sure if Drupal will allow this.)
  * How maps get into PB (curated from literature, attempt to select most important)
  * Overview of the types of maps in PB (chancy because it will be static text and will get outdated quickly).
  * List of consensus maps? These will change less, however, with SNP maps coming, how important are they, still?
  * List of maps that share markers? Would need to be dynamically generated.
  * Too many maps to list them all here, especially via static HTML.
  * Would prefer to put download options on the map record pages, or in cmap-js, not on this page.

Comments requested. @amcooksey @adf-ncgr @cann0010

**Comment by amcooksey** [comment]
My thoughts:
explanation of map and mapping population names
link to search should be good enough as long as it's reasonably obvious. 
how maps get into PB
download options on record pages AND cmap-js, not here
I would try to avoid having lists of anything...unless that's something we think people REALLY want.

**Comment by adf-ncgr** [comment]
I agree. Overviews of process/policy are appropriate and links to places on the site where content
can be searched/viewed. I could imagine at some point getting a dynamically generated overview of content (something along the lines of what Connor's DataStore summary does for genomes now). We should probably also link to the appropriate places in the mines here; if there isn't an appropriate template query now, we can certainly provide one.

**Comment by ekcannon** [comment]
Here's a thought: rather than dedicate a whole static page to map information, why not put the information in an expandable div on the search page. Something like this:
https://peanutbase-stage.usda.iastate.edu/chado/featuremap

One advantage to this approach would be having the information version controlled in GitHub rather than in a Drupal table. Another would be to streamline the navigation as someone clicking on a "map" link almost for sure wants to find maps. Also more amenable to a dynamically-generated overview as embedding php code in text that's saved in a Drupal table is less than ideal.

**Comment by ekcannon** [comment]
Removed maps over view page entirely. All the relevant information is on the maps search page, and Data Store downloads are in preparation for all maps. These will show on individual map pages.
